raw_data_path: "data/raw/hour.csv"
processed_data_path: "data/processed/features.csv"

features:
  drop_columns: ["instant", "dteday", "casual", "registered"]
  target: "cnt"


train:
  model_name: "bike_sharing_model"
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  model_path: "models/model.pkl"